'use strict'

const providersBy = {
  email: ['gravatar', 'github'],
  username: [
    'apple-music',
    'behance',
    'bluesky',
    'deviantart',
    'discord',
    'dribbble',
    'facebook',
    'github',
    'gitlab',
    'instagram',
    'ko-fi',
    'linkedin',
    'mastodon',
    'medium',
    'onlyfans',
    'openstreetmap',
    'patreon',
    'pinterest',
    'printables',
    'psnprofiles',
    'reddit',
    'snapchat',
    'soundcloud',
    'spotify',
    'steam',
    'substack',
    'telegram',
    'threads',
    'tiktok',
    'tumblr',
    'twitch',
    'vimeo',
    'x',
    'xboxgamertag',
    'youtube'
  ],
  domain: ['microlink']
}

module.exports = ctx => {
  const providers = {
    'apple-music': require('./apple-music')(ctx),
    behance: require('./behance')(ctx),
    bluesky: require('./bluesky')(ctx),
    deviantart: require('./deviantart')(ctx),
    discord: require('./discord')(ctx),
    dribbble: require('./dribbble')(ctx),
    duckduckgo: require('./duckduckgo')(ctx),
    facebook: require('./facebook')(ctx),
    github: require('./github')(ctx),
    gitlab: require('./gitlab')(ctx),
    google: require('./google')(ctx),
    gravatar: require('./gravatar')(ctx),
    instagram: require('./instagram')(ctx),
    'ko-fi': require('./ko-fi')(ctx),
    linkedin: require('./linkedin')(ctx),
    mastodon: require('./mastodon')(ctx),
    medium: require('./medium')(ctx),
    microlink: require('./microlink')(ctx),
    onlyfans: require('./onlyfans')(ctx),
    openstreetmap: require('./openstreetmap')(ctx),
    patreon: require('./patreon')(ctx),
    pinterest: require('./pinterest')(ctx),
    printables: require('./printables')(ctx),
    psnprofiles: require('./psnprofiles')(ctx),
    reddit: require('./reddit')(ctx),
    snapchat: require('./snapchat')(ctx),
    soundcloud: require('./soundcloud')(ctx),
    spotify: require('./spotify')(ctx),
    steam: require('./steam')(ctx),
    substack: require('./substack')(ctx),
    telegram: require('./telegram')(ctx),
    threads: require('./threads')(ctx),
    tiktok: require('./tiktok')(ctx),
    tumblr: require('./tumblr')(ctx),
    twitch: require('./twitch')(ctx),
    vimeo: require('./vimeo')(ctx),
    whatsapp: require('./whatsapp')(ctx),
    x: require('./x')(ctx),
    xboxgamertag: require('./xboxgamertag')(ctx),
    youtube: require('./youtube')(ctx)
  }

  return { providers, providersBy }
}
