'use strict'

const providersBy = {
  email: ['gravatar', 'github'],
  username: [
    'apple-music',
    'apple-store',
    'behance',
    'bluesky',
    'buymeacoffee',
    'codepen',
    'cults3d',
    'deviantart',
    'discord',
    'dockerhub',
    'dribbble',
    'facebook',
    'flickr',
    'github',
    'gitlab',
    'google-play',
    'huggingface',
    'instagram',
    'ko-fi',
    'linkedin',
    'mastodon',
    'medium',
    'npm',
    'onlyfans',
    'openstreetmap',
    'patreon',
    'pinterest',
    'printables',
    'producthunt',
    'psnprofiles',
    'reddit',
    'snapchat',
    'soundcloud',
    'spotify',
    'stackoverflow',
    'steam',
    'substack',
    'telegram',
    'thingiverse',
    'threads',
    'tiktok',
    'tumblr',
    'twitch',
    'vimeo',
    'x',
    'xboxgamertag',
    'youtube'
  ],
  domain: ['microlink']
}

module.exports = ctx => {
  const providers = {
    'apple-music': require('./apple-music')(ctx),
    'apple-store': require('./apple-store')(ctx),
    behance: require('./behance')(ctx),
    bluesky: require('./bluesky')(ctx),
    buymeacoffee: require('./buymeacoffee')(ctx),
    codepen: require('./codepen')(ctx),
    cults3d: require('./cults3d')(ctx),
    deviantart: require('./deviantart')(ctx),
    discord: require('./discord')(ctx),
    dockerhub: require('./dockerhub')(ctx),
    dribbble: require('./dribbble')(ctx),
    duckduckgo: require('./duckduckgo')(ctx),
    facebook: require('./facebook')(ctx),
    flickr: require('./flickr')(ctx),
    github: require('./github')(ctx),
    gitlab: require('./gitlab')(ctx),
    google: require('./google')(ctx),
    'google-play': require('./google-play')(ctx),
    gravatar: require('./gravatar')(ctx),
    huggingface: require('./huggingface')(ctx),
    instagram: require('./instagram')(ctx),
    'ko-fi': require('./ko-fi')(ctx),
    linkedin: require('./linkedin')(ctx),
    mastodon: require('./mastodon')(ctx),
    medium: require('./medium')(ctx),
    microlink: require('./microlink')(ctx),
    npm: require('./npm')(ctx),
    onlyfans: require('./onlyfans')(ctx),
    openstreetmap: require('./openstreetmap')(ctx),
    patreon: require('./patreon')(ctx),
    pinterest: require('./pinterest')(ctx),
    printables: require('./printables')(ctx),
    producthunt: require('./producthunt')(ctx),
    psnprofiles: require('./psnprofiles')(ctx),
    reddit: require('./reddit')(ctx),
    snapchat: require('./snapchat')(ctx),
    soundcloud: require('./soundcloud')(ctx),
    spotify: require('./spotify')(ctx),
    stackoverflow: require('./stackoverflow')(ctx),
    steam: require('./steam')(ctx),
    substack: require('./substack')(ctx),
    telegram: require('./telegram')(ctx),
    thingiverse: require('./thingiverse')(ctx),
    threads: require('./threads')(ctx),
    tiktok: require('./tiktok')(ctx),
    tumblr: require('./tumblr')(ctx),
    twitch: require('./twitch')(ctx),
    vimeo: require('./vimeo')(ctx),
    whatsapp: require('./whatsapp')(ctx),
    x: require('./x')(ctx),
    xboxgamertag: require('./xboxgamertag')(ctx),
    youtube: require('./youtube')(ctx)
  }

  return { providers, providersBy }
}
